name: Node CI

on:
  push:
    branches: [ ProjectService ]


jobs:
  Test:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm i
      - run: ng test
