name: Node CI

on:
  push:
    branches: [ ProjectService ]
  pull_request:
    branches: [ ProjectService ]

jobs:
  test:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm install
      - run: ng test
