name: CI/CD pour front Angular

on:
  push:
    branches: [frontOff]

jobs:
  test-and-build-angular:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du code
        uses: actions/checkout@v3

      - name: Installer Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Installer les dépendances npm
        run: npm install --legacy-peer-deps --force

      - name: Builder le projet Angular sans vérification des budgets
        run: npm run build -- --optimization=false --aot=false --budgets=false

      - name: Sauvegarder l'artefact Angular
        uses: actions/upload-artifact@v3
        with:
          name: front_app
          path: dist/
